apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  namespace: web
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec: 
      # initContainers:
      #   - name: debug
      #     image: 
      containers:
        - name: movies
          image: erikdelimavicente/rotten-potatoes:v1
          ports:
            - containerPort: 5000
          env: 
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: mongo-service.db.svc.cluster.local
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWORD
              value: mongopwd

---

apiVersion: v1
kind: Service
metadata:
  name: movies-service
  namespace: web
spec:
  selector:
    app: movies
  ports: 
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: LoadBalancer
 
